name: cd aks 1

on:
  push:
    branches: [ main ]


jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     #Set Kubernetes context (Azure AKS)
     - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}' # Azure credentials
        resource-group: 'nestor'
        cluster-name: 'nestor-aks'
      id: login

    # Deploy to Azure AKS using kubernetes
    - uses: Azure/k8s-deploy@v1
      with:
        namespace: default
       #Specify what manifest file or files to use
        manifests: |
          .k8s/test.yml
        #This will replace any image in manifest files with this 
        #specific version
        images: |
          nestoracr.azurecr.io/nestor:74db03c46674a6bcbb2d2357f6e36c228fb20c03

