name: Build and push the tagged build to production

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  build_push_image:
    runs-on: python:3.7.2-stretch

    steps:
      - uses: actions/checkout@v2

      - name: Fetch latest version
        id: fetch_version
        run: echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: nestoracr.azurecr.io
          username: nestoracr
          password: r=6Fvd56pKi7ouaDoXukvTO7yN4=T7aQ

      - name: Build and push production images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: nestoracr.azurecr.io/nestor:${{ steps.fetch_version.outputs.TAG }}
          push: true

  deploy:
    runs-on: python:3.7.2-stretch
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Resource group name
          resource-group: nestor
          # AKS cluster name
          cluster-name: nestor-aks

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace production \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=nestoracr.azurecr.io \
            --set dns.name=${{ secrets.DNS_NAME }} \
            --set image.tag=${GITHUB_REF##*/}
          
