name: Build and push the latest build

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
    runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: nestoracr.azurecr.io
          username: nestoracr
          password: r=6Fvd56pKi7ouaDoXukvTO7yN4=T7aQ

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: nestoracr.azurecr.io/nestor:latest
          push: true
